name: ðŸš€ Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  #  lint:
  #    name: â¬£ ESLint
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: ðŸ›‘ Cancel Previous Runs
  #        uses: styfle/cancel-workflow-action@0.9.1
  #
  #      - name: â¬‡ï¸ Checkout repo
  #        uses: actions/checkout@v3
  #
  #      - name: âŽ” Setup node
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: 14
  #
  #      - name: ðŸ“¥ Download deps
  #        uses: bahmutov/npm-install@v1
  #
  #      - name: ðŸ”¬ Lint
  #        run: npm run lint
  #
  #  typecheck:
  #    name: Ê¦ TypeScript
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: ðŸ›‘ Cancel Previous Runs
  #        uses: styfle/cancel-workflow-action@0.9.1
  #
  #      - name: â¬‡ï¸ Checkout repo
  #        uses: actions/checkout@v3
  #
  #      - name: âŽ” Setup node
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: 14
  #
  #      - name: ðŸ“¥ Download deps
  #        uses: bahmutov/npm-install@v1
  #
  #      - name: ðŸ”Ž Type check
  #        run: npm run typecheck --if-present
  #
  #  vitest:
  #    name: âš¡ Vitest
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: ðŸ›‘ Cancel Previous Runs
  #        uses: styfle/cancel-workflow-action@0.9.1
  #
  #      - name: â¬‡ï¸ Checkout repo
  #        uses: actions/checkout@v3
  #
  #      - name: âŽ” Setup node
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: 14
  #
  #      - name: ðŸ“¥ Download deps
  #        uses: bahmutov/npm-install@v1
  #
  #      - name: âš¡ Run vitest
  #        run: npm run test -- --coverage
  #
  #  cypress:
  #    name: âš«ï¸ Cypress
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: ðŸ›‘ Cancel Previous Runs
  #        uses: styfle/cancel-workflow-action@0.9.1
  #
  #      - name: â¬‡ï¸ Checkout repo
  #        uses: actions/checkout@v3
  #
  #      - name: ðŸ„ Copy test env vars
  #        run: cp .env.example .env
  #
  #      - name: âŽ” Setup node
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: 14
  #
  #      - name: ðŸ“¥ Download deps
  #        uses: bahmutov/npm-install@v1
  #
  #      - name: ðŸ— Build
  #        run: npm run build
  #
  #      - name: ðŸŒ³ Cypress run
  #        uses: cypress-io/github-action@v2
  #        with:
  #          start: npm run dev
  #          wait-on: "http://localhost:8811"
  #        env:
  #          PORT: "8811"

  deploy-staging:
    #needs: [lint, typecheck, vitest, cypress]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: staging

    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.1

      - name: ðŸ‘€ Env
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Git ref:    ${{ github.ref }}"
          echo "GH actor:   ${{ github.actor }}"
          echo "SHA:        ${{ github.sha }}"
          VER=`node --version`; echo "Node ver:   $VER"
          VER=`npm --version`; echo "npm ver:    $VER"

      - name: ðŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn

      - name: ðŸ— Build Packages
        run: |
          cat > .env << EOF
          NODE_ENV="${{ secrets.NODE_ENV }}"
          SESSION_SECRET="${{ secrets.SESSION_SECRET }}"
          EOF
          cat .env
          yarn build 

      - name: ðŸ›  Install Arc
        run: yarn global add @architect/architect

      - name: ðŸš€ Staging Deploy
        if: github.ref == 'refs/heads/dev'
        run: arc deploy --staging --prune
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-production:
    #needs: [lint, typecheck, vitest, cypress]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.1

      - name: ðŸ‘€ Env
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Git ref:    ${{ github.ref }}"
          echo "GH actor:   ${{ github.actor }}"
          echo "SHA:        ${{ github.sha }}"
          VER=`node --version`; echo "Node ver:   $VER"
          VER=`npm --version`; echo "npm ver:    $VER"

      - name: ðŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn

      - name: ðŸ— Build Packages
        run: yarn build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

      - name: ðŸ›  Install Arc
        run: yarn global add @architect/architect

      - name: ðŸš€ Production Deploy
        if: github.ref == 'refs/heads/main'
        run: arc deploy --production --prune
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
